resolver: lts-16.1
packages:
- .
extra-deps:
- github: lehins/hip
  commit: 1f4226a77b244d78a955536c7c163a79fd7238b8
  subdirs:
    - hip
    - ihaskell-hip
- massiv-0.5.2.0
- massiv-io-0.3.0.1
- Color-0.2.0
